-- Starlim multiempresa - etapa compatible
-- Crea la tabla base de tenants sin tocar datos existentes.

CREATE TABLE IF NOT EXISTS public.empresas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    cuit TEXT,
    plan TEXT NOT NULL DEFAULT 'base',
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    afip_pto_vta TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE public.empresas IS
    'Empresas/clientes SaaS. Tabla base para aislar datos por tenant.';
