"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { presentationPriceForLine } from "@/lib/presentation-pricing";

type Product = { id:string; code:string; name:string; imageUrl:string|null; presentationUnits:number; available:number; usualQuantity:number; purchaseCount:number; prices:Record<string,number> };
type Offer = { id:string; name:string; priceMode:string; fixedPrice:number|null; discountPercent:number|null; items:{productId:string;productName:string;quantity:number}[] };
type Data = { customer:{id:string;name:string;selectedList:string;payment_term_days:number|null}; lists:string[]; products:Product[]; recommendations:string[]; repeatItems:{productId:string;quantity:number}[]; offers:Offer[] };
type Cart = Record<string,number>;
const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS"});

function browserClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;return url&&key?createClient(url,key,{auth:{persistSession:true}}):null;}

export function PortalOrderBuilder({clientId,repeatSaleId}:{clientId:string;repeatSaleId:string}){
  const supabase=useMemo(()=>browserClient(),[]);
  const [session,setSession]=useState<Session|null>(null); const [data,setData]=useState<Data|null>(null); const [cart,setCart]=useState<Cart>({});
  const [query,setQuery]=useState(""); const [list,setList]=useState(""); const [payment,setPayment]=useState<"cuenta_corriente"|"contado">("cuenta_corriente");
  const [photo,setPhoto]=useState<Product|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [sending,setSending]=useState(false); const [created,setCreated]=useState("");
  useEffect(()=>{supabase?.auth.getSession().then(({data:auth})=>setSession(auth.session));},[supabase]);
  useEffect(()=>{if(!session||!clientId)return; const qs=new URLSearchParams({clientId}); if(repeatSaleId)qs.set("repeatSaleId",repeatSaleId); fetch(`/api/portal/order-builder?${qs}`,{headers:{authorization:`Bearer ${session.access_token}`},cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);return p.data as Data;}).then(value=>{setData(value);setList(value.customer.selectedList);setCart(Object.fromEntries(value.repeatItems.map(item=>[item.productId,item.quantity])));}).catch(e=>setError(e instanceof Error?e.message:"No pudimos preparar el pedido")).finally(()=>setLoading(false));},[session,clientId,repeatSaleId]);
  const productsById=useMemo(()=>new Map((data?.products??[]).map(p=>[p.id,p])),[data]);
  const rows=useMemo(()=>Object.entries(cart).filter(([,qty])=>qty>0).map(([id,qty])=>({product:productsById.get(id)!,qty})).filter(r=>r.product),[cart,productsById]);
  const price=(p:Product)=>p.prices[list]??Object.values(p.prices)[0]??0;
  const pricing=(p:Product,qty:number)=>presentationPriceForLine({prices:p.prices,priceListName:list,presentationUnits:p.presentationUnits,quantity:qty});
  const total=rows.reduce((sum,row)=>sum+pricing(row.product,row.qty).subtotal,0);
  const recommended=(data?.recommendations??[]).map(id=>productsById.get(id)).filter((p):p is Product=>Boolean(p));
  const results=query.trim()?data?.products.filter(p=>`${p.name} ${p.code}`.toLowerCase().includes(query.trim().toLowerCase())).slice(0,20)??[]:recommended;
  const benefits=(data?.offers??[]).flatMap(offer=>{const missing=offer.items.map(item=>({...item,missing:Math.max(0,item.quantity-(cart[item.productId]??0))})).filter(item=>item.missing>0); const hasSome=offer.items.some(item=>(cart[item.productId]??0)>0); return hasSome&&missing.length?[{offer,missing}]:[];});
  const presentationBenefits=rows.flatMap(({product,qty})=>{const detail=pricing(product,qty);return detail.unitsToNextPresentation?[{product,missing:detail.unitsToNextPresentation}]:[];});
  const setQty=(id:string,qty:number)=>setCart(current=>({...current,[id]:Math.max(0,Math.floor(qty||0))}));
  async function submit(){if(!session||!data||!rows.length)return;setSending(true);setError("");try{const response=await fetch("/api/portal/order-builder",{method:"POST",headers:{authorization:`Bearer ${session.access_token}`,"content-type":"application/json"},body:JSON.stringify({clientId:data.customer.id,list,paymentMethod:payment,items:rows.map(r=>({productId:r.product.id,quantity:r.qty}))})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setCreated(payload.data.quoteNumber);}catch(e){setError(e instanceof Error?e.message:"No pudimos enviar el pedido");}finally{setSending(false);}}
  if(!clientId)return <Centered text="Volvé al portal y elegí una sucursal."/>;
  if(loading)return <Centered text="Preparando tu pedido…"/>;
  if(error&&!data)return <Centered text={error}/>;
  if(!data)return null;
  if(created)return <Centered text={`Pedido ${created} recibido. Starlim lo revisará y podrás seguirlo desde tu portal.`} action="Volver a mi portal"/>;
  return <main className="min-h-screen bg-[#f3f7fc] text-[#172033]">
    <header className="sticky top-0 z-30 border-b border-white/20 bg-[#075ac7] px-5 py-3 text-white shadow-md"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><Link href="/portal"><Image alt="Starlim" className="h-auto w-28" height={52} src="/starlim-logo-white.png" width={140}/></Link><div className="text-right"><strong className="block">{data.customer.name}</strong><Link className="text-sm text-white/80 hover:text-white" href="/portal">← Volver al portal</Link></div></div></header>
    <div className="mx-auto grid max-w-6xl gap-5 px-4 py-6 lg:grid-cols-[minmax(0,1fr)_360px]">
      <section className="grid content-start gap-5">
        <div><span className="text-xs font-black uppercase tracking-[.13em] text-[#075ac7]">Pedido para cliente</span><h1 className="mt-1 text-3xl font-black">{repeatSaleId?"Revisá y ajustá tu último pedido":"Armá tu pedido en pocos pasos"}</h1><p className="mt-2 text-[#64748b]">Buscá sólo lo que necesitás. Tus productos habituales aparecen primero.</p></div>
        <div className="rounded-2xl border border-[#dbe5f1] bg-white p-4 shadow-sm"><label className="text-sm font-extrabold" htmlFor="product-search">Buscar producto</label><input autoFocus className="mt-2 min-h-12 w-full rounded-xl border border-[#bcd0e7] px-4 text-base outline-none focus:border-[#075ac7] focus:ring-2 focus:ring-blue-100" id="product-search" onChange={e=>setQuery(e.target.value)} placeholder="Ej.: detergente, rejilla o código" value={query}/><p className="mt-2 text-xs font-semibold text-[#64748b]">{query?"Resultados de búsqueda":"Recomendados según tus compras habituales"}</p></div>
        <div className="grid gap-2">{results.map(product=><article className="grid grid-cols-[56px_minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border border-[#dbe5f1] bg-white p-3 shadow-sm" key={product.id}><button aria-label={`Ver foto de ${product.name}`} className="grid h-14 w-14 place-items-center overflow-hidden rounded-xl bg-[#eef4fb]" onClick={()=>setPhoto(product)} type="button">{product.imageUrl?<Image alt={product.name} className="h-full w-full object-contain" height={64} src={product.imageUrl} unoptimized width={64}/>:<span className="text-xl">🧴</span>}</button><div className="min-w-0"><strong className="block truncate">{product.name}</strong><span className="text-xs text-[#64748b]">{product.code||"Sin código"} · Stock <b className={product.available>0?"text-emerald-700":"text-red-600"}>{product.available>0?product.available:"sin existencia"}</b></span><span className="mt-1 block font-black text-[#075ac7]">{money.format(price(product))}</span></div><button className="min-h-10 rounded-xl bg-[#075ac7] px-4 text-sm font-extrabold text-white" onClick={()=>setQty(product.id,(cart[product.id]??0)||(product.usualQuantity||1))} type="button">{cart[product.id]?"Agregado":"Agregar"}</button></article>)}</div>
      </section>
      <aside className="grid content-start gap-4 lg:sticky lg:top-24 lg:max-h-[calc(100vh-7rem)] lg:overflow-y-auto">
        <section className="rounded-3xl border border-[#cbdbea] bg-white p-5 shadow-lg"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Tu pedido</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-[#075ac7]">{rows.length} productos</span></div>{rows.length?<div className="mt-4 grid gap-3">{rows.map(({product,qty})=><div className="grid grid-cols-[minmax(0,1fr)_92px_28px] items-center gap-2 border-b border-[#e7eef6] pb-3" key={product.id}><div className="min-w-0"><strong className="block truncate text-sm">{product.name}</strong><span className="text-xs text-[#64748b]">{money.format(pricing(product,qty).subtotal)}</span></div><input aria-label={`Cantidad de ${product.name}`} className="h-10 rounded-lg border border-[#bfd0e4] px-2 text-center font-bold" min="1" onChange={e=>setQty(product.id,Number(e.target.value))} type="number" value={qty}/><button aria-label={`Quitar ${product.name}`} className="text-xl text-red-500" onClick={()=>setQty(product.id,0)} type="button">×</button></div>)}</div>:<p className="mt-4 rounded-xl bg-[#f4f7fb] p-4 text-sm text-[#64748b]">Todavía no agregaste productos.</p>}
          <label className="mt-4 grid gap-1 text-xs font-extrabold">Lista de precios<select className="h-11 rounded-xl border border-[#bfd0e4] bg-white px-3" onChange={e=>setList(e.target.value)} value={list}>{data.lists.map(name=><option key={name}>{name}</option>)}</select></label>
          <fieldset className="mt-4"><legend className="text-xs font-extrabold">Forma de pago</legend><div className="mt-2 grid grid-cols-2 gap-2"><Choice active={payment==="cuenta_corriente"} label="Cuenta corriente" onClick={()=>setPayment("cuenta_corriente")}/><Choice active={payment==="contado"} label="Contado" onClick={()=>setPayment("contado")}/></div></fieldset>
          <div className="mt-5 flex items-end justify-between border-t border-[#dbe5f1] pt-4"><span className="font-bold">Total estimado</span><strong className="text-2xl">{money.format(total)}</strong></div><p className="mt-1 text-xs text-[#64748b]">El equipo comercial confirmará disponibilidad y condición final.</p>{error?<p className="mt-3 text-sm font-bold text-red-600">{error}</p>:null}<button className="mt-4 min-h-12 w-full rounded-xl bg-[#075ac7] font-black text-white disabled:opacity-50" disabled={!rows.length||sending} onClick={submit} type="button">{sending?"Enviando pedido…":"Enviar pedido"}</button>
        </section>
        <section className="rounded-3xl border border-amber-200 bg-amber-50 p-5"><div className="flex items-center justify-between"><h2 className="font-black">Beneficios no aprovechados</h2><span className="rounded-full bg-amber-200 px-2.5 py-1 text-xs font-black">{benefits.length+presentationBenefits.length+(payment==="cuenta_corriente"?1:0)}</span></div><div className="mt-3 grid gap-3">{presentationBenefits.map(({product,missing})=><div className="rounded-xl bg-white p-3" key={`presentation-${product.id}`}><strong className="text-sm">Precio mejorado por presentación</strong><p className="mt-1 text-xs text-[#64748b]">Agregá {missing} {missing===1?"unidad":"unidades"} de {product.name} para completar {product.presentationUnits} y acceder al precio mejorado.</p><button className="mt-2 text-xs font-black text-[#075ac7]" onClick={()=>setQty(product.id,(cart[product.id]??0)+missing)} type="button">Completar presentación →</button></div>)}{benefits.map(({offer,missing})=><div className="rounded-xl bg-white p-3" key={offer.id}><strong className="text-sm">{offer.name}</strong><p className="mt-1 text-xs text-[#64748b]">Agregá {missing.map(item=>`${item.missing} ${item.productName}`).join(" + ")} para completar la promoción.</p><button className="mt-2 text-xs font-black text-[#075ac7]" onClick={()=>missing.forEach(item=>setQty(item.productId,(cart[item.productId]??0)+item.missing))} type="button">Aprovechar beneficio →</button></div>)}{payment==="cuenta_corriente"?<button className="rounded-xl bg-white p-3 text-left" onClick={()=>setPayment("contado")} type="button"><strong className="text-sm">Consultar precio de contado</strong><span className="mt-1 block text-xs text-[#64748b]">Elegí contado para que el equipo aplique el beneficio vigente.</span></button>:null}{benefits.length===0&&presentationBenefits.length===0&&payment==="contado"?<p className="text-sm text-amber-900">No hay otros beneficios pendientes para esta selección.</p>:null}</div></section>
      </aside>
    </div>{photo?<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-5" onClick={()=>setPhoto(null)} role="presentation"><div className="max-w-lg rounded-3xl bg-white p-5" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><div className="flex items-start justify-between gap-5"><strong>{photo.name}</strong><button onClick={()=>setPhoto(null)} type="button">✕</button></div>{photo.imageUrl?<Image alt={photo.name} className="mt-4 max-h-[65vh] w-full object-contain" height={600} src={photo.imageUrl} unoptimized width={600}/>:<p className="mt-5 text-[#64748b]">Este producto todavía no tiene una foto cargada.</p>}</div></div>:null}
  </main>;
}
function Choice({active,label,onClick}:{active:boolean;label:string;onClick:()=>void}){return <button className={`min-h-11 rounded-xl border px-2 text-sm font-bold ${active?"border-[#075ac7] bg-blue-50 text-[#075ac7]":"border-[#ccd9e8] bg-white"}`} onClick={onClick} type="button">{label}</button>}
function Centered({text,action}:{text:string;action?:string}){return <main className="grid min-h-screen place-items-center bg-[#f3f7fc] p-5"><div className="max-w-md rounded-3xl bg-white p-8 text-center shadow-xl"><Image alt="Starlim" className="mx-auto h-auto w-32 rounded-xl bg-[#075ac7] p-3" height={60} src="/starlim-logo-white.png" width={150}/><p className="mt-6 font-bold">{text}</p>{action?<Link className="mt-5 inline-flex rounded-xl bg-[#075ac7] px-5 py-3 font-black text-white" href="/portal">{action}</Link>:null}</div></main>}
