export type VerifiedProductImageSource = {
  productId: string;
  productName: string;
  brand: string;
  sourcePage: string;
  sourceUrl: string;
};

// Every entry is manually checked against the exact product, variety and presentation.
// The API only imports URLs declared here; clients cannot provide arbitrary remote URLs.
export const VERIFIED_PRODUCT_IMAGE_SOURCES: VerifiedProductImageSource[] = [
  {
    productId: "968a46db-f046-48c4-8ba8-b15c0ae7393e",
    productName: "BLEM AEROSOL LIMÓN ACERO/METAL 360 ML",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/expert-care/aerosol-lemon",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/cuidado-experto/acero-inoxidable-y-metal-limon-en-aerosol/pledge_ar-7_25-acerio_inoxidable_y_metal_limon_aerosol.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "c1ebd9a4-a4b9-43ba-91a7-ffb59db6d7cc",
    productName: "BLEM AEROSOL NARANJA GRANITO 360 ML",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/expert-care/aerosol-orange",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/cuidado-experto/granito-y-marmol-naranja-en-aerosol/pledge_ar-7_25-granito_marmol_naranja_aerosol.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "471c8b00-66bf-4c66-8dd1-93cee3714acc",
    productName: "BLEM MADERA LAVANDA 360 ML/12 AR",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/expert-care/aerosol-lavender",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/limpieza-diaria/lustramuebles-lavanda-en-aerosol/pledge_ar-7_25-lustramuebles_lavanda_aerosol.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "68f2a0e6-4d74-40c1-ad2f-72acfa8afe97",
    productName: "BLEM MADERA ORIGINAL 360 ML/12 AR",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/expert-care/aerosol-original",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/cuidado-experto/lustramuebles-original-en-aerosol/pledge_ar-7_25-lustramuebles_original_aerosol.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "64c42c98-c3ba-4dfa-acc8-b3f0d2701e23",
    productName: "BLEM MULTI GATILLO CITRUS 400 ML/12 AR",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/everyday-clean/ph-balanced-multisurface-cleaner-spray-citrus",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/2025/pledge_ar_multi_citrus_spray.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "66cea9a4-e93b-417f-8b24-6fab5a91d6d7",
    productName: "BLEM MULTI GATILLO FLORAL 400 ML/12 AR",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/everyday-clean/multisurface-and-electronics-floral-spray",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/2025/pledge_ar_multi_floral_spray.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "789e86a6-f370-4370-a946-6b2e8907d433",
    productName: "BLEM RENUEVA MADERA PREMIUM ARGÁN 360 ML",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/expert-care/renewing-aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/cuidado-experto/lustramuebles-argan-en-aerosol/pledge_ar-7_25-lustramuebles_argan_aerosol.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "202fddeb-9de3-41d0-9f84-5cecfbcf1c87",
    productName: "LYSOFORM AERO ON THE GO ORIGINAL 55 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/aerosoles/para-llevar/lysoform_ar-7_25-aerosol_para_llevar-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "3b93f8d4-2592-43f3-a763-5fb2f443fc19",
    productName: "LYSOFORM AEROSOL BEBÉ 360 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/lysoform_ar-9_25-aerosol_desinfectante_bebe-285.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "ddff6a9f-83e6-4b29-b6a3-a3b2a0834c08",
    productName: "LYSOFORM AEROSOL LAVANDA 285 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-aerosol-lavanda-285.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "eebfa98f-e3ec-4e0a-a6b1-c66a2d35cc36",
    productName: "LYSOFORM AEROSOL ULTRALIVIANO LAVANDA 315 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante-ultraliviano",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/aerosoles/ultraliviano-lavanda/lysoform_ar-7_25-aerosol_ultraliviano_lavanda-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "9525d9ea-3d32-4eb9-85bf-e8efb706deaa",
    productName: "LYSOFORM AEROSOL LAVANDA 360 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/aerosoles/lavanda/lysoform_ar-7_25-aerosol_lavanda-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "f8fe0b9f-4a2f-46b5-9655-296d48779b0c",
    productName: "LYSOFORM AEROSOL LAVANDA 495 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-aerosol-lavanda-495.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "f04d6d8a-8016-472d-aaab-0323ad8a20d7",
    productName: "LYSOFORM AEROSOL ORIGINAL 285 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-aerosol-original-285.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "52a24ee0-6b29-470e-b658-b6420e2e5231",
    productName: "LYSOFORM AEROSOL ULTRALIVIANO ORIGINAL 315 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/air-care/aerosol-desinfectante-ultraliviano",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/aerosoles/ultraliviano-original/lysoform_ar-7_25-aerosol_ultraliviano_original-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "24c44076-a265-4172-902d-5491dd4977d4",
    productName: "LYSOFORM BAÑO DOYPACK 450 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/bano",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-bano-dp-450.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "cf4074bc-2d1d-4a47-8e33-4a0bb5401508",
    productName: "LYSOFORM BAÑO GATILLO 500 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/bano",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/limpiadores/bano/lysoform_ar-7_25-limpiadores_bano-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "5b569768-35bf-4ec0-91cb-ba02f3ff7d57",
    productName: "LYSOFORM CONCENTRADO BEBÉ DOYPACK 420 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/limpiador-desinfectante-concentrado",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/limpiadores/concentrado-bebe/lysoform_ar-7_25-limpiadores_concentrado_bebe-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "230b3158-db0a-4350-baa3-f3135a8262d2",
    productName: "LYSOFORM CONCENTRADO CÍTRICA DOYPACK 420 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/limpiador-desinfectante-concentrado",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/limpiadores/concentrado-citrus/lysoform_ar-7_25-limpiadores_concentrado_citrus-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "c09aeb50-a09e-49fd-938b-e1c81f3887de",
    productName: "LYSOFORM CONCENTRADO LAVANDA DOYPACK 420 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/limpiador-desinfectante-concentrado",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-limpiador-desinfectante-concentrado-lavanda-420.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "53470edf-e2d2-4755-8d5b-85e1d0a6f443",
    productName: "LYSOFORM CONCENTRADO ORIGINAL DOYPACK 420 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/limpiador-desinfectante-concentrado",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-limpiador-desinfectante-concentrado-original-420.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "717c3f3e-e0d7-4bb7-b8da-08beb786be07",
    productName: "LYSOFORM CREMOSO 450 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/crema-multiuso",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/limpiadores/crema-multiuso/lysoform_ar-7_25-crema_multiuso-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "4ff9851b-ae09-4d87-b29c-11aebae27659",
    productName: "LYSOFORM LIMPIADOR LÍQUIDO LAVANDA BOTELLA 800 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/limpiador-desinfectante-concentrado",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/limpiadores/concentrado-lavanda/lysoform_ar-7_25-limpiadores_concentrado_lavanda-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "a3436130-bf6c-4306-a74d-5538f1a495e5",
    productName: "LYSOFORM LIMPIADOR LÍQUIDO ORIGINAL BOTELLA 800 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/limpiador-desinfectante-concentrado",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/product-detail-pages/limpiadores/concentrado-original/lysoform_ar-7_25-limpiadores_concentrado_original-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "1704b46c-f0a8-4082-bc44-3f66abf0f34c",
    productName: "LYSOFORM MULTISUPERFICIES DOYPACK 450 ML",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/multisuperficies",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/10-10-25/lysoform-multisuperficies-dp-450.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "f15b3951-8f00-44ec-9f27-b8dc5c59c6ff",
    productName: "PATO BLOQUE PARA MOCHILA 12 X 80 GR",
    brand: "Pato",
    sourcePage: "https://patopurific.com.ar/es-ar/products/cistern-block/purific-backpack-block",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/duck/argentina/product-detail-pages/cistern-block/pato_ar-6_25-pastila_para_mochilo_duo-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "00de9c66-861f-437d-8156-a60749cfa6ce",
    productName: "PATO BLOQUE PARA MOCHILA 24 X 40 GR",
    brand: "Pato",
    sourcePage: "https://patopurific.com.ar/es-ar/products/cistern-block/purific-backpack-block",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/duck/argentina/product-detail-pages/cistern-block/pato_ar-6_25-pastila_para_mochilo-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "7d9112e2-8f69-4a25-9e6c-61873deba304",
    productName: "PATO DISCO ADHESIVO MARINA APARATO 12 X 36ML",
    brand: "Pato",
    sourcePage: "https://patopurific.com.ar/es-ar/products/fresh-discs/marina",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/duck/argentina/product-detail-pages/fresh-disc-marina/pato_ar-6_25-marina_repuesto_23_36ml-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "7418acb3-166c-4889-9835-97c07a628709",
    productName: "PATO GEL LIMPIADOR MARINA 100 % DESTRUCTOR DE SARRO",
    brand: "Pato",
    sourcePage: "https://patopurific.com.ar/es-ar/products/limescale/gel-limpiador",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/duck/argentina/product-detail-pages/limescale---gel-limpiador/pato_ar-6_25-100_distructor_de_sarro-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "fd859361-ed1c-47a7-9ab6-fb018c1901ac",
    productName: "PATO PURIFIC BLOQUE ADHESIVO PARA INODOROS CITRUS",
    brand: "Pato",
    sourcePage: "https://patopurific.com.ar/es-ar/products/fresh-strips/citrus",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/duck/argentina/product-detail-pages/fresh-strips/pato_ar-6_25-fresh_strip-cirtus-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "183099a5-f980-475c-a6e1-e9a76b852e33",
    productName: "GLADE ACEITES NATURALES REP VAINILLA 21 ML",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/continuous/scented-oil-plugins/sheer-vanilla-embrace-repuesto",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/oils/encanto-de-vainilla-aceites-naturales-repuesto/glade_ar-3_25-oil-encanto_de_vainilla_naturales-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "ae271b69-92b8-47f2-a110-05994b573af2",
    productName: "Glade Aero Placer floral360ml/6 AR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/odor-fighting-soft-mist-aerosol-spray/blooming-peony-cherry",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/instant-action-spray/placer-floral-y-frutos-rojos/glade_ar-3_25-spray-placer_floral-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "52effc17-29d2-441a-a5ae-376223d348e3",
    productName: "Glade APC Lavanda 12x875ML AR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/multisurface/multisuperficies-limpiador/lavender-fields",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/multisuperficies-limpiador/glade_ar-4_25-campos_de_lavanda-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "9457dd8f-935c-4934-b5bb-65e8bbb6c174",
    productName: "GLADE AUTOMATICO REP LIMON 170ML",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/continuous/automatic-spray/lemon-fresh-repuesto",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/automatic-spray/limon-refrescante-automatico-repuesto/glade_ar-3_25-spray-limon_refrescante_repuesto-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "1e6a8a3d-545d-4ac8-bb2e-d3779e1502da",
    productName: "GLADE AUTOSPORT FULL ACQUA",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/auto-care/sport/aqua-waves",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/oils/aqua-glade-auto-sport/glade_ar-3_25-oil-aqua_glade_auto_sport-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "a5d7b882-5e2a-4d3b-8888-98f25f6caebd",
    productName: "GLADE AUTOSPORT REP ACQUA 7 ML",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/auto-care/sport/aqua-waves-repuesto",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/oils/aqua-glade-auto-sport-repuesto/glade_ar-3_25-oil-aqua_glade_auto_sport_repuesto-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "4a848ad5-b3f6-4ff3-a683-847ce5537d9c",
    productName: "GLADE AUTOSPORT FULL AUTO NUEVO 7 ML",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/auto-care/sport/new-car",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/oils/auto-nuevo-glade-auto-sport/glade_ar-3_25-oil-auto_nuevo_glade_auto_sport-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "d15a054c-c477-4b94-a0e5-a10c111796a5",
    productName: "GLADE MINIGEL LAVANDA 70GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/continuous/mini-gels/lavender",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/gel/home-gels/campos-de-lavanda/glade_ar-3_25-gel-campos_de_lavanda-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "7070a7b4-dbc1-4e71-a7a7-9f63d652ee96",
    productName: "GLADE MINIGEL PLACER FLORAL Y FR 70GR/12 AR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/continuous/mini-gels/blooming-peony-cherry",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/gel/home-gels/placer-floral-y-frutos-rojos/gladear325gelplacerfloralfrutosrojos1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "01ce1c3d-db25-4eb4-8666-2cd3a76fc45f",
    productName: "GLADE TOQUE FULL LIMÓN REFRESCANTE 9GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/touch-fresh-minispray/lemon-fresh-starter-kit",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/mini-spray-touch/limon-refrescante-toque/glade_ar-3_25-spray-limon_toque-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "51720f70-d191-4442-b658-03447a0627b5",
    productName: "Glade Toque Limón Rep. x2",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/touch-fresh-minispray/lemon-fresh-2-repuestos",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/mini-spray-touch/limon-refrescante-toque-2-repuestos/glade_ar-3_25-spray-limon_toque_repuesto_2-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "1afe1909-14b6-4793-92cd-259d9e287396",
    productName: "GLADE TOQUE REP LAVANDA 9GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/touch-fresh-minispray/lavender-repuesto",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/mini-spray-touch/lavanda/glade_ar-3_25-spray-lavanda-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "b510e81b-4e79-4e78-b0ae-c8d83ced61e2",
    productName: "GLADE TOQUE REP LIMON 9GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/touch-fresh-minispray/lemon-fresh-repuesto",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/mini-spray-touch/limon-refrescante-toque-repuesto/glade_ar-3_25-spray-limon_toque_repuesto-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "3d155faa-7994-4367-a47a-afb29b213e32",
    productName: "Raid 4 Toques Sin Olor 43.7ml/12 AR",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/4-toques",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/2026-dsc-updates/jan-2026-update/product-detail-pages/raid_ar-1_26-aerosol-4_toques-1.webp?h=1080&iar=0&w=1920&sc_lang=es-ar",
  },
  {
    productId: "84365f21-4688-480b-b7c0-8a6ef55cf533",
    productName: "RAID CASA Y JARDIN AERO 360ML/12",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/casa-y-jardin",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/2026-dsc-updates/jan-2026-update/product-detail-pages/raid_ar-1_26-raid-casa_y_jardin-1.webp?h=1080&iar=0&w=1920&sc_lang=es-ar",
  },
  {
    productId: "bb486aee-743d-45e9-a678-0f356595d458",
    productName: "RAID EXTERMINADOR AERO 360ML/12 AR",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/extermina-cucarachas",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/2026-dsc-updates/jan-2026-update/product-detail-pages/raid_ar-1_26-extermina_cucarachas-1.webp?h=1080&iar=0&w=1920&sc_lang=es-ar",
  },
  {
    productId: "7db12922-bd95-48b1-82c5-74b2e81d1503",
    productName: "RAID MAX MATA CUCARACHAS SIN OLOR 360 ML",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/max-mata-cucarachas-y-aranas",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/pdp-images/product-detail-pages/max-mata-cucarachas-y-aranas/raid_ar-4_25-max_mata_cucarachas_y_aranas-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "51ce4824-0d0e-4aec-b022-7ef738adf578",
    productName: "RAID MMM MAX AERO 360 ML/12",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/max-mata-moscas-mosquitos-y-zancudos",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/pdp-images/product-detail-pages/max-mata-moscas-mosquitos-y-zancudos/raid_ar-4_25-max_mata_moscas-mosquitos_en_10-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "e6d761aa-00b6-4247-bfc3-0ac9470ffd31",
    productName: "RAID MMM SIN OLOR AERO 360 ML/12",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/mata-moscas-y-mosquitos-sin-olor",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/2026-dsc-updates/jan-2026-update/product-detail-pages/raid_ar-1_26-mata_moscas_mosquitos_y_zancudos-1.webp?h=1080&iar=0&w=1920&sc_lang=es-ar",
  },
  {
    productId: "e9ddf9a2-952e-4f13-b6a1-69c89d99bd78",
    productName: "RAID PULGAS Y LARVAS AERO 390 ML",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/aerosol/mata-pulgas-y-garrapatas",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/pdp-images/product-detail-pages/mata-pulgas-y-garrapatas/raid_ar-4_25-mata_pulgas_y_garrapatas-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "9f5dacdc-b805-4449-aed9-fd53706e835c",
    productName: "RAID TABLETAS APARATO SIN CABLE + 4 TABLETAS",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/electric-mats/aparato-para-tabletas",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/pdp-images/product-detail-pages/aparato-para-tabletas/raid_ar-4_25-aparato_para_tabletas-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "8e187b5c-9f36-432e-bdad-284d1bf28b97",
    productName: "RAID TABLETAS REP X 12",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/electric-mats/tabletas",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/pdp-images/product-detail-pages/electric-mats_tabletas/raid_ar-4_25-tabletas-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "9687927f-8e28-4a1e-8cc9-6773c59bc6f1",
    productName: "OFF EXTRA DURACION AERO 170CM/12 AR",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/extra-duracion/aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/extra-duracion/aerosol/off_arg-6_24-extra_duracion-aerosol-image_2.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "27ab4ffe-877f-472f-ac25-84d2bb8eb560",
    productName: "OFF FAMILY CREMA 60G/12 AR.",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/family/family-crema",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/family/crema-60-gr/off_arg-6_24-family-crema_60-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "70875422-298e-4c8e-bc70-6c0e2fde21e6",
    productName: "OFF INVISIBLE KIDS 113ML /12",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/con-icaridina/kids-spray",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/con-icaridina/kids-spray/off_arg-6_24-con_icaridina-kids_spray-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "9e6181f5-d390-4fec-8035-a501a12c320a",
    productName: "OFF INVISIBLE SUENOS 113ML /12",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/con-icaridina/suenos-spray",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/con-icaridina/suenos-spray/off_arg-6_24-con_icaridina-suenos_spray-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "48773053-9074-44f9-9538-955d77fa3458",
    productName: "OFF! AEROSOL FAMILY 170 ML",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/family/family-aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/family/aerosol-170-cm3/off_arg-6_24-family-aerosol_170-image_2.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "68444208-05ea-43a1-84e4-9f891b495861",
    productName: "OFF! DEFENSE BEBE GEL 100ML/12 AR",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/defense/defense-bebe-gel",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/defense/bebe-gel-100-ml/off_arg-6_24-defense-bebe_gel-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "cc4afd19-efc8-41ca-af5e-37c1884caf79",
    productName: "OFF! DEFENSE EXTREME GEL 100ML",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/defense/defense-extreme-tube",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/defense/extreme-gel/off_arg-6_24-defense-extreme_gel-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "92ec4454-a817-422d-90ff-ea972c22fe13",
    productName: "OFF! DEFENSE INFANTIL SPRAY 100ML",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/defense/defense-infantil-spray",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/defense/infantil-spray-100-ml/off_arg-6_24-defense-infantil_spray-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "abe915be-0900-45ca-a075-1c4b9ce0eccd",
    productName: "OFF! INVISIBLE ACTIVE 104.51ML /12",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/con-icaridina/proteccion-invisible-active-aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/con-icaridina/invisible-active-aerosol/off_arg-6_24-con_icaridina-invisibale_active_aerosol-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "c767770f-17fe-4b8f-8b22-41946266230b",
    productName: "OFF! INVISIBLE EVERYDAY 104.51ML /12",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/con-icaridina/proteccion-invisible-aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/con-icaridina/invisible-everyday-aerosol/off_arg-6_24-con_icaridina-invisibale_everyday_aerosol-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "e8f62c32-a583-4436-b215-26eaea9802c7",
    productName: "MM aerosol limpia vidrios 360 ML/12/AR",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/whole-house/glass-window-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/vidrios-y-multisuperficies/mr_muscle_ar-6_25-vidrios-glass_cleaner_360ml-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "30f348dd-c140-4432-bdb8-485d426c74a4",
    productName: "MR MUSCULO ANTIGRASA COCINA DP 450 ML",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/kitchen/orange-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/cocina/mr_muscle_ar-6_25-cocina_5450cm3-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "9aa87ce2-587d-4e06-a765-52b49bd53291",
    productName: "MR MUSCULO ANTIGRASA COCINA DP 900 ML",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/kitchen/orange-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/cocina/mr_muscle_ar-6_25-cocina_900cm3-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "8e701962-dbef-4ad4-84a7-8eafec74e900",
    productName: "MR MUSCULO BAÑO TR 12X500ML AR",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/bath/bathroom-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/bano/mr_muscle_ar-6_25-bano_500cm3.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "6beab2d4-470d-4147-8fe1-2aa7353c258d",
    productName: "MR MUSCULO CREMA CITRUS 450 ML",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/bath/bathroom-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/bano/mr_muscle_ar-6_25-bano-creama_citrus_450cm3-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "61dc09b9-6769-43f8-aab6-36b5c5464e3d",
    productName: "MR MUSCULO EXTRA POWER COCINA GAT 500 ML",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/kitchen/extra-power-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/cocina/mr_muscle_ar-6_25-cocina-extra_power_500cm3-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "00673d0f-3400-4c97-9f4a-d0b68582c4fc",
    productName: "MR MUSCULO VIDRIOS Y MULTIUSO DP 450 ML",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/whole-house/glass-window-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/vidrios-y-multisuperficies/mr_muscle_ar-6_25-vidrios-glass_cleaner_450ml-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "cb6cba37-d8b3-40e3-b743-354ffae68ee3",
    productName: "MR MUSCULO VIDRIOS Y MULTIUSO TR 500CM3/12 AR",
    brand: "Mr. Músculo",
    sourcePage: "https://mrmuscleclean.com/es-ar/products/whole-house/glass-window-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/mrmuscle/argentina/product-detail-pages/vidrios-y-multisuperficies/mr_muscle_ar-6_25-vidrios-glass_cleaner_500ml-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "bba48666-fcb6-414d-83b0-512fc9e0a981",
    productName: "FUYI LIQUIDO ELECTRICO FULL 32,9 ML",
    brand: "Fuyi",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/fuyi/insecto-volador-liquido-electrico/fuyi-liquido-electrico-full-sin-olor",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/355457.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "3749418f-4f00-4ff8-883c-4adfa2efdaa8",
    productName: "FUYI REPELENTE AERO 12 X 170ML",
    brand: "Fuyi",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/fuyi/repelente/fuyi-repelente-aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/355347.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "e3354952-04f6-4643-a176-507779e056a5",
    productName: "FUYI TABLETAS REP X12",
    brand: "Fuyi",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/fuyi/insecto-volador-tableta/fuyi-tabletas-contra-mosquitos",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/355390.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "ea3d5987-3662-432c-8063-5f711c1868eb",
    productName: "CERAMICOL AERO LAVANDA 360 ML/12 AR",
    brand: "Ceramicol",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/ceramicol/lustramuebles/ceramicol-lustramuebles-aerosol-lavanda",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/368925.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "f9f763ec-cbc1-46a3-ba02-d3bcdb145b09",
    productName: "CERAMICOL AEROSOL NARANJA 360 ML",
    brand: "Ceramicol",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/ceramicol/lustramuebles/ceramicol-lustramuebles-aerosol-naranja",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/368927.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "3bbcdb93-e765-4700-8c03-bc8c5f747b64",
    productName: "CERAMICOL AEROSOL ORIGINAL 360ML/12 AR",
    brand: "Ceramicol",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/ceramicol/lustramuebles/ceramicol-lustramuebles-aerosol",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/368923.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "42211e08-11b8-4c02-b1aa-ba8dbe64a5f5",
    productName: "CERAMICOL LAMPAZOL 860 ML",
    brand: "Ceramicol",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/ceramicol/pisos/ceramicol-limpia-pisos-lampazol-citrus",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/341744.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "d878affd-50f6-4d60-9777-e4fded6e12dd",
    productName: "CERAMICOL PISOS PLASTIFICADOS 875 ML",
    brand: "Ceramicol",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/ceramicol/pisos/ceramicol-pisos-plastificados-y-flotantes-floral",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/wiscj/products/argentina/341743.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "efd20f6e-bcd1-4187-9fc5-515b3d0cb821",
    productName: "Baygon Mata Cucarachas y Aranas Aero 300",
    brand: "Baygon",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/baygon/aerosol/extermina-cucarachas-y-aranas",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/baygon/argentina/product-detail-pages/extermina-cucarachas-y-aranas/baygon_ar-5_25-aerosol-extermina_cucarachas-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "3d236f05-8c37-46cd-a62c-dd1e436ecd5b",
    productName: "BAYGON MATA MOSCAS Y MOSQUITOS AERO 300ML/12 AR",
    brand: "Baygon",
    sourcePage: "https://whatsinsidescjohnson.com/es-ar/brands/baygon/aerosol/mata-moscas-y-mosquitos",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/baygon/argentina/product-detail-pages/mata-moscas-y-mosquitos/baygon_ar-5_25-aerosol-mata_moscas-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "b94fb27a-efa9-4bd8-a300-ff8d871e609e",
    productName: "BLEM EC LIMPIA P&F ALMENDRA BT 800 ML/12/AR",
    brand: "Blem",
    sourcePage: "https://blem.com.ar/es-ar/products/expert-care/soapy-wood-cleaner",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/pledge/argentina/product-detail-pages/cuidado-experto/pisos-plastificados-y-flotantes/pledge_ar-7_25-pios_plastificados_flotanes.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "bdb1e305-deb8-4eda-abcd-add6a5ed8d54",
    productName: "LYSOFORM SOLUCION TOTAL FLORAL P 8X1760",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/solucion-total",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/lysoform-solucion-total/lysoform_ar-9_25-solucion_total_floral-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "077608b3-91ed-405c-a013-a9ef1185408d",
    productName: "Lysoform Solución Total Lavanda 8X1760ml",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/solucion-total",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/lysoform-solucion-total/lysoform_ar-9_25-solucion_total_lavanda-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "a6de1132-2c7f-4d65-ba7d-b4cbb575ebf0",
    productName: "Lysoform Solución Total Bosque de Pino 8x1760ml AR",
    brand: "Lysoform",
    sourcePage: "https://lysoform.com.ar/es-ar/products/home-cleaning-disinfecting/solucion-total",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/lysoform/argentina/dsc-images/updated-product-detail-images/home-cleaning-disinfecting/lysoform-solucion-total/lysoform_ar-9_25-solucion_total_bosque-1.webp?h=990&iar=0&w=1760",
  },
  {
    productId: "d6a11303-a878-47fc-8802-2a238a032011",
    productName: "Off Spray Family 177 ML/12 AR",
    brand: "OFF!",
    sourcePage: "https://off.com.ar/es-ar/product/family/family-spray",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/off/argentina/product-detail-pages/family/spray-177-ml/off_arg-6_24-family-spray_177-image_1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "7cc1db58-40f9-4c80-ab66-f9447a3e63f1",
    productName: "RAID ESPIRALES VERDE SOBRES 4 X 12 X 4UN",
    brand: "Raid",
    sourcePage: "https://raid.com.ar/es-ar/products/coils/espirales",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/raid/argentina/pdp-images/product-detail-pages/espirales-4-unidades/raid_ar-4_25-espirales_4_unidades-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "c820315f-2996-4512-91a3-c1e1346bf896",
    productName: "GLADE MINIGEL CAR ACQUA 70GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/auto-care/gel/aqua-waves",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/gel/car-gels/aqua/glade_ar-3_25-gel-aqua-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "3e522682-a9b8-45a7-8862-dc8b8aed9682",
    productName: "GLADE MINIGEL LIMÓN 70GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/auto-care/gel/citrus",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/gel/car-gels/citrus/glade_ar-3_25-gel-citrus-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "2afb5582-3778-4b67-a5a7-371dec28e32a",
    productName: "GLADE TOQUE REP LAVANDA 2X9GR - TWINPACK",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/touch-fresh-minispray/lavender-2-repuestos",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/mini-spray-touch/campos-de-lavanda-toque-2-repuestos/glade_ar-3_25-spray-campo_de_lavanda_repuesto_2-1.webp?h=1080&iar=0&w=1920",
  },
  {
    productId: "293b0e29-94e5-4f27-a394-893c7f5f1db9",
    productName: "GLADE TOQUE REP PLACER FLORAL Y FRUTOS ROJOS 9GR",
    brand: "Glade",
    sourcePage: "https://glade.com/es-ar/products/instantaneous/touch-fresh-minispray/blooming-peony-cherry-repuesto",
    sourceUrl: "https://edge.sitecorecloud.io/scjohnsonana080-dart-production-40df/media/project/dart/glade/argentina/images/pdp-images/sprays/mini-spray-touch/placer-floral-y-frutos-rojos/glade_ar-3_25-spray-placer_floral-1.webp?h=1080&iar=0&w=1920",
  },
];

export function verifiedProductImageSource(productId: string) {
  return VERIFIED_PRODUCT_IMAGE_SOURCES.find((entry) => entry.productId === productId) ?? null;
}
